app: serverlessforstripe
service: my-node-app

provider:
  name: aws
  runtime: nodejs20.x
  deploymentBucket:
    name: stripe-deployment
  stage: dev
  region: us-east-1
  environment:
    STRIPE_SECRET_KEY: ${env:STRIPE_SECRET_KEY}

  httpApi:
    cors:
      allowedOrigins:
        - http://localhost:3000  # or '*' for any origin
      allowedHeaders:
        - Content-Type
        - Authorization
        - X-Amz-Date
        - X-Api-Key
        - X-Amz-Security-Token
      allowedMethods:
        - OPTIONS
        - POST
        - GET
      allowCredentials: false

plugins:
  - serverless-dotenv-plugin

functions:
  app:
    handler: index.handler
    events:
      - httpApi:
          path: /create-payment-intent
          method: post

package:
  exclude:
    - .gitignore
    - .git/**